---
kind: pipeline
type: docker
name: default

platform: 
    os: linux
    arch: arm64

steps:
- name: test
  image: node
  commands:
  - npm install 
  - npm test

- name: docker
  image: plugins/docker
  settings:
    repo: sylvainleroux/crawler
    auto_tag: true
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    
