#!/bin/bash

CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S")
echo $CURRENT_DATE
echo "Launch bank-crawler"

cd /Users/sleroux/ideo/bank-crawler/

# Clean up files

rm -Rf step_*
rm -f frameContent
rm -f download-url

# Launch crawler

/usr/local/bin/phantomjs test.js

export URL=`cat download-url`
export DATE=$(date +"%Y%m%d%H%m%s")
export FILENAME="/Users/sleroux/Downloads/CyberPlus_OP_$DATE.csv"
curl -s -L -b cookies -c cookies $URL -o "$FILENAME"


# Compare file


# move file to dropbox dir
