version: '3'
services:
    crawler:
        build:
            context: .
            dockerfile: Dockerfile
        image: sleroux/crawler
        container_name: crawler
        restart: unless-stopped
        shm_size: '1gb'
        expose:
            - 9222
            - 9229
        environment:
            - CHROME_EXEC=/usr/bin/chromium-browser
            - NODE_ENV=${NODE_ENV}
            - MYSQL_BANK_HOST=${MYSQL_BANK_HOST}
            - MYSQL_BANK_USERNAME=${MYSQL_BANK_USERNAME}
            - MYSQL_BANK_PASSWORD=${MYSQL_BANK_PASSWORD}
            - MYSQL_BANK_DB=${MYSQL_BANK_DB}
            - CRON_RULE=* * * * *
            - CREDENTIALS_LOGIN=${CREDENTIALS_LOGIN}
            - CREDENTIALS_PWD=${CREDENTIALS_PWD}
            - FILE_REPOSITORY=/home/pptruser/Downloads
        volumes:
            - ./downloads:/home/pptruser/Downloads

        command: node index.js
